### ISSUE TITLE
MuJoCo errors

### ISSUE THREAD

**Issue by jmichaux** [jmichaux/intrinsic-motivation#1]
### The Error
I'm getting the following error in MuJoCo:

`raise MujocoException('Got MuJoCo Warning: {}'.format(warn)) mujoco_py.builder.MujocoException: Got MuJoCo Warning: Nan, Inf or huge value in QACC at DOF 0. The simulation is unstable. Time = 0.4000.`

Based on [this](http://www.mujoco.org/forum/index.php?threads/got-mujoco-warning-nan-inf-or-huge-value-in-qacc-at-dof-0-the-simulation-is-unstable-time-0-51.3683/), [this](http://www.mujoco.org/forum/index.php?threads/warning-nan-inf-or-huge-value-in-qacc-at-dof-1.3540/), [this](https://github.com/openai/mujoco-py/issues/340), and [this](http://www.mujoco.org/forum/index.php?threads/debugging-instability.3909/) the error is due to **time-stepping** or **actions that are too large**.

### My observations
There are two things that I noticed:
1. The Entropy increases over time, from 27 to 165
2. The actions predicted by the network are quite large, like 1e7 around time the bug occurs

### Reproducing the bug
First install the repo. Then, to reproduce the bug starting from the very beginning of training run

`python main.py `

To reproduce the bug starting at a later point in the training run

`python main.py --debug`

### Questions for debugging

1. Why does it mater that the actions are large?  The environment clips the actions. See below:

https://github.com/jmichaux/multimodal-curiosity/blob/c507206a79595573fcd808cebcf60f98d26789db/multimodal_curiosity/envs/robot_env.py#L63

2. Will I get errors if I always feed in zeros for the actions?
 - If I load the bad model, it doesn't matter if all the actions are zero. I still see the bug.

3. What if I change the environment?
 - I see the same error if I use FetchReachDense-v1 and FetchPushDense-v1

4. Is my cpu the problem?

5. Do I need to normalize the observations?

**Comment by sadegh16** [comment]
> There was an issue with the action log probabilitie. [This commit ](https://github.com/jmichaux/multimodal-curiosity/commit/74a8e653ea81e54e34ec364d1a91699f09b7a789) solved the issue.

could you help me with this error?

`mujoco_py.builder.MujocoException: Unknown warning type Time = 0.0000.Check for NaN in simulation.`

I am using python 3.6.12 ( I cannot change because of dependencies)
